config/routes.rb
Rails.application.routes.draw do
  resources :message_groups
  resources :messages
  resources :blockeds
  root 'home#index'
  resources :friendships, only: %i[index new destroy] do
    get 'header', on: :collection
    delete 'remove', on: :collection, to: 'friendships#destroy'
  end

  resources :users do
    patch '/set_status', to: 'users#set_status'
  end

  resources :user_chatrooms, only: [:destroy]
  
  resources :available_friendships, only: %i[index]

  resources :friendship_requests do
    post 'accept', on: :member
  end

  resources :chatrooms do
    post 'direct', on: :collection
  end

  namespace :sessions do
    resources :signin, only: %i[new create]
    resources :signup, only: %i[new create]
    delete '/signout', to: 'signout#destroy'
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :message_group

  validate :no_empty_message
  has_many_attached :attachments, dependent: :destroy

  private

    def no_empty_message
      errors.add(:content, "Mensagem não pode ser vazia") if content.empty? && attachments.count.zero?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  def index
    @messages = Message.all
  end

  def show
    @pos = params[:pos]
  end

  def new
    @message = Message.new
  end

  def edit
    @pos = params[:pos]
  end

  def create
    message = Message.new(message_params)
    user_chatroom = UserChatroom.find_by(user_id: @current_user.id, chatroom_id: params[:message][:chatroom_id])
    message_group = MessageGroup
                      .joins(:user_chatroom)
                      .where(user_chatrooms: { chatroom_id: params[:message][:chatroom_id]})
                      .order(created_at: :desc)
                      .first
    
    message.message_group_id = begin
      if message_group && message_group.user_chatroom_id == user_chatroom.id
        message_group.id
      else
        MessageGroup.create(user_chatroom_id: user_chatroom.id).id
      end
    end

    respond_to do |format|
      if message.save
        Turbo::StreamsChannel.broadcast_append_to "chatroom_#{params[:message][:chatroom_id]}_message_groups", target: "message_groups", partial: "message_groups/message_group", locals: { user: @current_user, message_group: message.message_group }

        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  def update
    @pos = params[:pos]
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to messages_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @attachment_ids = @message.attachments.pluck(:id)
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:message_group_id, :content, attachments: [])
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def user_avatar(user)
    return image_tag user.avatar, class: 'rounded-circle', width: 40, height: 40 if user.avatar.attached?
    tag.i class: "bi bi-person-check", style: 'font-size: 28px;'
  end
end

app/views/messages/_form.html.erb
<%= form_with(model: message, data: { controller: 'message' }) do |form| %>
  <%= hidden_field_tag :pos, pos %>
  <%= form.text_area :content %>
  <p>
    ctrl para <%= link_to("cancelar", message_path(message, pos: pos), class: 'link-primarys') %>
    ° enter para <%= form.submit "salvar", class: "link-primary bg-transparent" %>
  </p>
<% end %>

app/views/messages/_message.html.erb
<div class="message__hover w-100" data-controller="message">
  <%= turbo_frame_tag message do %>
    <div class="d-flex position-relative w-100">
    
      <%= content_tag :div, class: "message__hidden message__container_buttons" do
        [
          link_to(edit_message_path(message, pos: i), class: 'btn btn-sm' ) do
            tag.i class: "bi bi-pencil-fill", style: 'color: #ffffff;'
          end,
          button_to(message_path(message), method: :delete, class: 'btn btn-sm') do
            tag.i class: "bi bi-trash-fill", style: 'color: #ffffff;'
          end
        ].join(" ").html_safe
      end %>
      <% if i > 0 %>
        <%= tag.span class: 'message__hidden message__created_hour' do %>
          <%= message.created_at.strftime("%H:%M") %>
        <% end %> 
      <% end %>
      <p class='m-0' style='font-size:15px;'><%= simple_format(message.content) %></p>
    </div>
  <% end %>
  <div class='d-flex position-relative w-100 message__hover' data-controller="modal">
    <% if message.attachments.count > 0 %>
      <div>
        <% message.attachments.each.with_index do |attachment, index| %>
          <% if attachment.image? %>
            <div class="message__attachments_container" id="attachment<%= attachment.id %>">
              <%= image_tag attachment, class: 'message__attachments_image', data: { action: "click->modal#show" } %>
              <div class="modal fade" id="<%= attachment.id %>Modal" tabindex="<%= index %>" aria-labelledby="<%= attachment.id %>ModalLabel" aria-hidden="true" data-action="blur->modal#hide">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <%= image_tag attachment %>
                  </div>
                </div>
              </div>
            </div>
          <% elsif attachment.video? %>
            <div class="message__attachments_container" id="attachment<%= attachment.id %>">
              <p class='message__attachments_video_title'>
                <span><%= attachment.filename %></span>
                <%= link_to url_for(attachment), download: true do %>
                  <i class="bi bi-download"></i>
                <% end %>
              </p>
              <%= video_tag url_for(attachment), class: 'message__attachments_video', controls: '' %>
            </div>
          <% elsif attachment.audio? %>
            <div>
              <div class="message__attachments_container" id="attachment<%= attachment.id %>">
                <div class="d-flex w-100">
                  <i class="bi bi-file-earmark-music" style='font-size:38px; color: #ffffff;'></i>
                  <p style='font-size: 15px;'>
                    <%= link_to attachment.filename, url_for(attachment), download: true %> <br />
                    <%= Utils::File.convert_byte_to_kilobyte(attachment.byte_size) %>
                  </p>
                </div>
                <%= link_to url_for(attachment), download: true do %>
                  <i class="bi bi-download" style='font-size:20px; color: #ffffff;'></i>
                <% end %>
              </div>
              <%= audio_tag url_for(attachment), class: 'message__attachments_audio', controls: '' %>
            </div>
          <% else %>
              <div class="message__attachments_container" id="attachment<%= attachment.id %>">
                <div class="d-flex w-100">
                  <i class="bi bi-file-earmark-pdf" style='font-size:38px; color: #ffffff;'></i>
                  <p style='font-size: 15px;'>
                    <%= link_to attachment.filename, url_for(attachment), download: true %> <br />
                    <%= Utils::File.convert_byte_to_kilobyte(attachment.byte_size) %>
                  </p>
                </div>
                <%= link_to url_for(attachment), download: true do %>
                  <i class="bi bi-download" style='font-size:20px; color: #ffffff;'></i>
                <% end %>
              </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/destroy.turbo_stream.erb
<%= turbo_stream.remove @message %>

<%= @attachment_ids.each do |attachment_id| %>
  <%= turbo_stream.remove "attachment#{attachment_id}" %>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>
<%= turbo_frame_tag @message do %>
  <%= render "form", message: @message, pos: @pos %>
<% end %>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag @message do %>
  <%= render @message, message: @message, i: @pos.to_i %>
<% end %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/messages/update.turbo_stream.erb
<%= turbo_stream.replace @message do %>
  <%= render @message, message: @message, i: @pos.to_i %>
<% end %>