config/routes.rb
Rails.application.routes.draw do
  resources :message_groups
  resources :messages
  resources :blockeds
  root 'home#index'
  resources :friendships, only: %i[index new destroy] do
    get 'header', on: :collection
    delete 'remove', on: :collection, to: 'friendships#destroy'
  end

  resources :users do
    patch '/set_status', to: 'users#set_status'
  end

  resources :user_chatrooms, only: [:destroy]
  
  resources :available_friendships, only: %i[index]

  resources :friendship_requests do
    post 'accept', on: :member
  end

  resources :chatrooms do
    post 'direct', on: :collection
  end

  namespace :sessions do
    resources :signin, only: %i[new create]
    resources :signup, only: %i[new create]
    delete '/signout', to: 'signout#destroy'
  end

end

app/models/friendship_request.rb
class FriendshipRequest < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :target, class_name: "User", foreign_key: "target_id"

  validates_uniqueness_of :sender_id, scope: [:target_id]
  validates_uniqueness_of :target_id, scope: [:sender_id]

  after_create_commit -> (friendship_request) {
    broadcast_append_to [friendship_request.sender, "friendship_requests"],
    target: "friendship_requests_container",
    partial: "friendship_requests/sender_friendship_request",
    locals: { friendship_request: friendship_request }

    broadcast_append_to [friendship_request.target, "friendship_requests"],
    target: "friendship_requests_container",
    partial: "friendship_requests/target_friendship_request",
    locals: { friendship_request: friendship_request }
  }

  after_commit -> (friendship_request) { 
    ActionCable.server.broadcast("pending_requests_#{friendship_request.target_id}", { total: FriendshipRequest.where(target_id: friendship_request.target_id).count })
  }
end

app/controllers/friendship_requests_controller.rb
class FriendshipRequestsController < ApplicationController
  before_action :set_friendship_request, only: %i[ accept destroy ]

  def index
    @target_friendship_requests = FriendshipRequest.where(target_id: @current_user).includes(:target)
    @sender_friendship_requests = FriendshipRequest.where(sender_id: @current_user).includes(:sender)
  end

  def new
    @friendship_request = FriendshipRequest.new
  end

  def accept
    if Friendship.create(user1: @friendship_request.sender, user2: @friendship_request.target)
      @friendship_request.destroy

      respond_to do |format|
        format.html { redirect_to friendship_requests_url, notice: 'Solicitação de amizade aceita!' }
        format.turbo_stream { flash.now[:notice] = 'Solicitação de amizade aceita!' }
      end
    else
      @friendship_request.errors.add(:base, 'Houve um erro ao tentar aceitar a solicitação de amizade')
      respond_to do |format|
        format.html { render :index }
        format.turbo_stream
      end
    end
  end

  def create
    @friendship_request = FriendshipRequest.new(sender: @current_user)
    new_friend = User.find_by(email: friendship_request_params[:email])

    unless new_friend
      @friendship_request.errors.add(:base, "Não foi possivel encontrar um usuario com este email")
      render :new, status: :unprocessable_entity
      return
    end
    @friendship_request.target = new_friend

    if @friendship_request.save
      flash.now[:notice] = "Solicitação de amizade enviada com sucesso"
      render :new
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @friendship_request.destroy
    Turbo::StreamsChannel.broadcast_remove_to [@friendship_request.sender, "friendship_requests"], target: @friendship_request
    Turbo::StreamsChannel.broadcast_remove_to [@friendship_request.target, "friendship_requests"], target: @friendship_request
    respond_to do |format|
      format.html { redirect_to friendship_requests_url, notice: "Friendship request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_friendship_request
      @friendship_request = FriendshipRequest.find(params[:id])
    end

    def friendship_request_params
      params.require(:friendship_request).permit(:email)
    end
end

app/helpers/friendship_requests_helper.rb
module FriendshipRequestsHelper
end

app/views/friendship_requests/_form.html.erb
<%= form_with model: FriendshipRequest.new, data: { controller: 'friend-request'} do |form| %>
  <% if friendship_request.errors.any? %>
    <div style="color: red">
      <ul>
        <% friendship_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if notice %>
    <p style="color: green"><%= notice %></p>
  <% end %>
  

  <%= field_set_tag nil, class: 'friendship_request__form__fieldset' do %>
    <%= form.text_field :email , placeholder: "Insira um email de usuario", data: { 'friend-request-target': 'email' } %>
    <%= form.button "Enviar pedido de amizade", class: "btn btn-primary", disabled: true %>
  <% end %>
  
<% end %>

app/views/friendship_requests/_sender_friendship_request.html.erb
<div id="<%= dom_id friendship_request %>">
  <div class='d-flex friendship_request__item w-100 justify-content-between'>
    <div class='d-flex'>
      <% if friendship_request.target.avatar.attached? %>
        <%= image_tag friendship_request.target.avatar, class: 'rounded-image', width: 40, height: 40 %>
      <% else %>
        <i class="bi bi-person-check" style='font-size: 28px; margin-right: 10px;'></i>
      <% end %>
      <div>
        <p class="m-0"><%= friendship_request.target.name %></p>
        <small>Pedido de amizade enviado</small>
      </div>
    </div class='d-flex'>
    <%= button_to friendship_request_path(friendship_request), method: :delete, class: 'rounded' do %>
      x    
    <% end %>
  </div>
</div>

app/views/friendship_requests/_target_friendship_request.html.erb
<div id="<%= dom_id friendship_request %>">
  <div class='d-flex friendship_request__item w-100 justify-content-between'>
    <div class='d-flex'>
      <% if friendship_request.target.avatar.attached? %>
        <%= image_tag friendship_request.target.avatar, class: 'rounded-image', width: 40, height: 40 %>
      <% else %>
        <i class="bi bi-person-check" style='font-size: 28px; margin-right: 10px;'></i>
      <% end %>
      <div>
        <p class="m-0"><%= friendship_request.target.name %></p>
        <small>Pedido de amizade recebido!</small>
      </div>
    </div>
    <div class='d-flex'>
      <%= button_to accept_friendship_request_path(friendship_request), class: 'rounded' do %>
        <i class="bi bi-check"></i>
      <% end %>
      <%= button_to friendship_request_path(friendship_request), method: :delete, class: 'rounded' do %>
        x    
      <% end %>
    </div>
  </div>
</div>

app/views/friendship_requests/accept.turbo_stream.erb
<% if @friendship_request.errors.any? %>
  <div style="color: red">
    <ul>
      <% @friendship_request.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <%= turbo_stream.append "flash_message" do %>
    <p style="color: green"><%= flash[:notice] %></p>
  <% end %>

  <%= turbo_stream.remove @friendship_request %>
<% end %>

app/views/friendship_requests/index.html.erb
<%= turbo_frame_tag "main" do %>
  <p style="color: green"><%= notice %></p>
  <%= turbo_frame_tag "flash_message" %>

  <h5 id='total_pending'>Pendente - <%= @target_friendship_requests.count + @sender_friendship_requests.count %></h5>

  <%= turbo_stream_from @current_user, "friendship_requests" %>
  <%= turbo_frame_tag "friendship_requests_container" do %>
    <% @target_friendship_requests.each do |friendship_request| %>
      <%= render "friendship_requests/target_friendship_request", friendship_request: friendship_request %>
    <% end %>
    
    <% @sender_friendship_requests.each do |friendship_request| %>
      <%= render "friendship_requests/sender_friendship_request", friendship_request: friendship_request %>
    <% end %>
  <% end %>
<% end %>

app/views/friendship_requests/new.html.erb
<%= turbo_frame_tag "main" do %>
  <div class="friendship_request__form">
    <h5>ADICIONAR AMIGO</h5>
    <small> Você pode adicionar amigos com o email deles </small>
    <%= render "form", friendship_request: @friendship_request %>
  </div>
<% end %>