config/routes.rb
Rails.application.routes.draw do
  resources :message_groups
  resources :messages
  resources :blockeds
  root 'home#index'
  resources :friendships, only: %i[index new destroy] do
    get 'header', on: :collection
    delete 'remove', on: :collection, to: 'friendships#destroy'
  end

  resources :users do
    patch '/set_status', to: 'users#set_status'
  end

  resources :user_chatrooms, only: [:destroy]
  
  resources :available_friendships, only: %i[index]

  resources :friendship_requests do
    post 'accept', on: :member
  end

  resources :chatrooms do
    post 'direct', on: :collection
  end

  namespace :sessions do
    resources :signin, only: %i[new create]
    resources :signup, only: %i[new create]
    delete '/signout', to: 'signout#destroy'
  end

end

app/views/shared/_chatroom.html.erb
<%= button_to chatroom_path(key), method: :get, id: "chatroom_url_#{key}", class: 'd-flex align-items-center justify-content-between border-0 w-100 nav-link chatroom__link', form: { class: 'friendships_form' } do %>
  <div class="d-flex align-items-center">
    <%= sidebar_user_avatars(values) %>
    <div class='ms-2' style="text-align: left; line-height: 18px;">
      <%= sidebar_user_names(values) %>
      <%= members_count(values) %>
    </div>
  </div>
  <%= tag.i class: "bi bi-x chatroom__remove_icon", data: { id: key } %>
<% end %>

app/views/shared/_counter_badge.html.erb
<div class="total_friendship_requests_received">
  <% if total&.positive? %>
    <span class="badge"><%= total %></span>
  <% end %>
</div>

app/views/shared/_direct_messages.html.erb
<%= turbo_frame_tag "direct_messages" do %>
  <div id="dropdown-element" class="dropdown-menu p-0" data-controller="direct-message" data-action="turbo:before-fetch-request->direct-message#hideDropdown">
    <%= form_with(model: Chatroom.new) do |form| %>
      <div class="direct_messages card">
        <p class="m-0 direct_messages__title">Selecionar amigos</p>
        <small class="direct_messages__subtitle">Você pode adicionar até mais 9 amigos</small>
        
        <div class="direct_messages__list">
          <% users.each do |user| %>
            <div class='d-flex align-items-center justify-content-between'>
              <div class='d-flex align-items-center'>
                <% if user.avatar.attached? %>
                  <%= image_tag user.avatar, class: 'rounded-image', width: 40, height: 40 %>
                <% else %>
                  <i class="bi bi-person-check" style='font-size: 28px; margin-right: 10px;'></i>
                <% end %>
                <div class="ms-2" style="line-height: 16px;">
                  <p class="m-0"><%= user.name %></p>
                </div>
              </div>
              <%= form.check_box :user_ids, { multiple: true }, user.id, nil %>
            </div>
          <% end %>
        </div>
        <hr>
        <%= form.submit "Criar grupo privado", class: "btn btn-primary w-100" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_friendship_status.html.erb
<%= tag.div(id: "friend_#{user.id}", class: "status status__#{User.statuses[user.status]}") %>

app/views/shared/_header.html.erb
<%= turbo_frame_tag "header_frame" do %>
  <nav class="navbar navbar-expand-lg w-100 header shadow">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-light active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="#">Pricing</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_sidebar.html.erb
<nav class="nav nav-pills" data-controller='sidebar'>
  <div class="d-flex flex-column flex-shrink-0 p-3 text-white vh-100 sidebar" style="width: 280px;">
    <hr>
    <%= button_to header_friendships_path, method: :get, class: 'd-flex align-items-center border-0 w-100 nav-link active', form: { class: 'friendships_form' } do %>
      <div class="d-flex justify-content-between">
        <div>
          <i class="bi bi-person-check"></i>
          <span> Amigos </span>
        </div>
        <%= turbo_stream_from @current_user, "total_friendship_requests_received" %>
        <%= render "shared/counter_badge", total: total_friendship_requests_received %>
      </div>
    <% end %>
    <div class="dropdown d-flex justify-content-between align-items-center">
      <span style="font-size: 14px;">MENSAGENS DIRETAS </span>
      <a href="#" data-bs-toggle="dropdown" style="font-size: 26px; text-decoration: none;" id="direct-messages-trigger">
        + 
      </a>
      <%= render "shared/direct_messages", users: @users %>
    </div>
    
    <%= turbo_stream_from "user_#{@current_user.id}_chatrooms" %>
    <%= turbo_frame_tag "chatrooms" do %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <% chatroom_groups.each do |key, values| %>
        <%= render "shared/chatroom", key: key, values: values %>
      <% end %>
    <% end %>
    <ul class="nav nav-pills flex-column mb-auto text-center"></ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <div class="position-relative me-2">
          <% if @current_user.avatar.attached? %>
            <%= image_tag @current_user.avatar, width: 32, height: 32, class: "rounded-circle" %>
          <% else %>
            <i class="bi bi-person-check" style='font-size: 28px;'></i>
          <% end %>
          <%= tag.div(id: "current_user_status", class: "status status__#{User.statuses[@current_user.status]}") %>
        </div>
        <strong><%= @current_user.name %></strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        
        <li>
          <%= button_to "Disponível", "/users/#{@current_user.id}/set_status?status=#{CGI::escapeHTML("disponivel")}", method: :patch, remote: true, data: { turbo: false }, class: "dropdown-item", style: 'color: green' %>
        </li>
        <li>
          <%= button_to "Ausente", "/users/#{@current_user.id}/set_status?status=#{CGI::escapeHTML("ausente")}", method: :patch, remote: true, data: { turbo: false }, class: "dropdown-item", style: 'color: red' %>
        </li>
        <li>
          <%= button_to "Não perturbar", "/users/#{@current_user.id}/set_status?status=#{CGI::escapeHTML("nao perturbar")}", method: :patch, remote: true, data: { turbo: false }, class: "dropdown-item", style: 'color: orange' %>
        </li>
        <li>
          <%= button_to "Offline", "/users/#{@current_user.id}/set_status?status=#{CGI::escapeHTML("offline")}", method: :patch, remote: true, data: { turbo: false }, class: "dropdown-item", style: 'color: gray' %>
        </li>
        <hr>
        <li>
          <%= button_to "Sair", '/sessions/signout', method: :delete, class: "dropdown-item" %>
        </li>
      </ul>
    </div>
  </div>
</nav>