config/routes.rb
Rails.application.routes.draw do
  resources :message_groups
  resources :messages
  resources :blockeds
  root 'home#index'
  resources :friendships, only: %i[index new destroy] do
    get 'header', on: :collection
    delete 'remove', on: :collection, to: 'friendships#destroy'
  end

  resources :users do
    patch '/set_status', to: 'users#set_status'
  end

  resources :user_chatrooms, only: [:destroy]
  
  resources :available_friendships, only: %i[index]

  resources :friendship_requests do
    post 'accept', on: :member
  end

  resources :chatrooms do
    post 'direct', on: :collection
  end

  namespace :sessions do
    resources :signin, only: %i[new create]
    resources :signup, only: %i[new create]
    delete '/signout', to: 'signout#destroy'
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user1, class_name: "User", foreign_key: "user1_id"
  belongs_to :user2, class_name: "User", foreign_key: "user2_id"

  enum status: { 
    available: 'disponivel',
    offline: 'offline',
    busy: 'não perturbar',
    unavailable: 'ausente'
  }

  validates_uniqueness_of :user1_id, scope: [:user2_id]
  validates_uniqueness_of :user2_id, scope: [:user1_id]
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :total_pending_friendships_request, only: [:header]
  before_action :friendship_users, only: [:index]

  def index
  end

  def new
  end

  def header
    friendship_users("and users.status = 'available'")
  end

  def destroy
    @friend_user_id = params[:user_id]

    friendship = Friendship.where(user1_id: @current_user.id, user2_id: @friend_user_id).or(Friendship.where(user1_id: @friend_user_id, user2_id: @current_user.id)).first
    friendship.destroy

    @friendship_users = @current_user.friendship_users
    @available_friendship_users = @current_user.friendship_users(extra_conditions: "and users.status = 'available'")

    respond_to do |format|
      format.html { redirect_to friendship_users_url, notice: "Amizade removida com sucesso" }
      format.turbo_stream { flash.now[:notice] = "Amizade removida com sucesso" }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_friendship_user.html.erb
<div id="<%= dom_id friendship_user %>">
  <div class='d-flex friendship__item w-100 justify-content-between'>
    <div class='d-flex'>
      <% if friendship_user.avatar.attached? %>
        <%= image_tag friendship_user.avatar, class: 'rounded-image', width: 40, height: 40 %>
      <% else %>
        <i class="bi bi-person-check" style='font-size: 28px; margin-right: 10px;'></i>
      <% end %>
      <div class="ms-2" style="line-height: 16px;">
        <p class="m-0"><%= friendship_user.name %></p>
        <small><%= friendship_user.status %></small>
      </div>
    </div>
    <div class='d-flex'>
      <%= button_to direct_chatrooms_path(target_id: friendship_user), class: 'rounded friendship__item__button' do %>
        <i class="bi bi-chat-left"></i>
      <% end %>
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none friendship__item__button" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-three-dots-vertical auto" style="margin: auto;"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
          <li>
            <%= button_to "Desfazer amizade", remove_friendships_path(user_id: friendship_user.id), method: :delete, class: "dropdown-item bg-transparent" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/friendships/_header.html.erb
<%= turbo_frame_tag "header_frame" do %>
  <nav class="navbar navbar-expand-lg w-100 header shadow" data-controller="header">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav nav nav-pills">
          <li class="nav-item">
            <div style='padding: 0.5rem;'>
              <i class="bi bi-person-check text-light"></i>
              <span class='text-light'> Amigos </span>
            </div>
          </li>
          <div class="vr"></div>
          <li class="nav-item">
            <a class="nav-link text-light active" href="/available_friendships" data-turbo-frame="main">Disponivel</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="/friendships" data-turbo-frame="main">Todos</a>
          </li>
          <li class="nav-item d-flex">
            <a class="nav-link text-light" href="/friendship_requests" data-turbo-frame="main">Pendente</a>
            <%= turbo_stream_from current_user, "total_friendship_requests_received" %>
            <%= render "shared/counter_badge", total: total_friendship_requests_received %>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="/blockeds" data-turbo-frame="main">Bloqueado</a>
          </li>
          <li class="nav-item">
            <%= link_to new_friendship_request_path, class: "nav-link text-light", style: "color: #46c46e !important;", data: { turbo_frame: "main" } do %>
              Adicionar Amigo
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/friendships/_total_friendship_users.html.erb
<%= turbo_frame_tag "total_friendship_users" do %>
  <h5 class='total_friendship_users'>TODOS OS AMIGOS - <%= friendship_users.count %></h5>
<% end %>

app/views/friendships/destroy.turbo_stream.erb
  <%= turbo_stream.append "flash_message" do %>
    <p style="color: green"><%= flash[:notice] %></p>
  <% end %>

  <%= turbo_stream.remove "user_#{@friend_user_id}" %>

  <%= turbo_stream.replace "total_friendship_users" do %>
    <%= render "friendships/total_friendship_users", friendship_users: @friendship_users %>
  <% end %>

  <%= turbo_stream.replace "total_available_friendships" do %>
    <%= render "available_friendships/total_available_friendships", friendship_users: @available_friendship_users %>
  <% end %>

app/views/friendships/header.html.erb
<%= render 'friendships/header', current_user: @current_user, total_friendship_requests_received: @total_friendship_requests_received %>

app/views/friendships/header.turbo_stream.erb
<%= turbo_stream.replace "header_frame" do %>
  <%= render 'friendships/header',
      current_user: @current_user,
      total_friendship_requests_received: @total_friendship_requests_received
  %>
<% end %>

<%= turbo_stream.replace "main" do %>
  <%= render "available_friendships/index", friendship_users: @friendship_users %>
<% end %>

app/views/friendships/index.html.erb
<%= turbo_frame_tag "main" do %>
  <p style="color: green"><%= notice %></p>
  <%= turbo_frame_tag "flash_message" %>

  <%= render "friendships/total_friendship_users", friendship_users: @friendship_users %>

  <%= turbo_stream_from @current_user, "friendship_users" %>
  <%= turbo_frame_tag "friendship_users_container" do %>
    <% @friendship_users.each do |friendship_user| %>
      <%= render "friendships/friendship_user", friendship_user: friendship_user %>
    <% end %>
  <% end %>
<% end %>

app/views/friendships/new.html.erb
<h1>Friendships#new</h1>
<p>Find me in app/views/friendships/new.html.erb</p>